spring:
    profiles:
    active:
     dev
---
server:
    port: 8201
spring:
    profiles: dev
    application: 
        name: springcloud-config-server
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8000/eureka/
---
server:
    port: 8202
spring:
    profiles: test
    application:
        name: springcloud-config-server
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8000/eureka/
